export const CBC_LEVELS = [
  "PP1",
  "PP2",
  "Grade 1",
  "Grade 2",
  "Grade 3",
  "Grade 4",
  "Grade 5",
  "Grade 6",
  "Grade 7",
  "Grade 8",
  "Grade 9",
  "Senior School",
] as const;

export const COUNTIES = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
] as const;

export const SUBJECTS = [
  "Mathematics",
  "English",
  "Kiswahili",
  "Kenyan Sign Language",
  "Indigenous Languages",
  "Science and Technology",
  "Integrated Science",
  "Social Studies",
  "Agriculture and Nutrition",
  "Home Science",
  "Creative Arts",
  "Creative Arts and Sports",
  "Physical and Health Education",
  "Religious Education",
  "Pre-Technical Studies",
  "Business Studies",
  "Computer Science",
  "Life Skills",
  "Pedagogy and Assessment",
  "Inclusive Education",
  "School Leadership",
  "Teacher Wellbeing",
  "Digital Skills and AI",
] as const;

const canon = (list: readonly string[], value: string) =>
  list.find((x) => x.toLowerCase() === value.trim().toLowerCase());
export const canonicalCounty = (value: string) =>
  canon(COUNTIES, value.replace(/\s+county$/i, "").replace(/[’`]/g, "'"));
export const canonicalLevel = (value: string) => canon(CBC_LEVELS, value);
export const canonicalSubject = (value: string) => canon(SUBJECTS, value);
