'use client'

import { useState } from 'react'
import { useConvex, useMutation } from 'convex/react'
import { api } from '@/convex/_generated/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { downloadXlsx, type Cell, type Sheet } from '@/lib/admin/xlsx'
import { Field, ReasonDialog, selectClass, useStaff } from '@/components/admin/common'
import { toast } from 'sonner'

const PAGE = 200
const MAX_ROWS = 50_000
const stamp = (ms: number) => (ms ? new Date(ms).toISOString().slice(0, 16).replace('T', ' ') : '')

/** Builds the Excel workbook in the browser: summary sheets from the counters, learner rows by walking pages. */
export function AnalyticsExport({ days, programs }: { days: number; programs: { id: string; title: string }[] }) {
  const convex = useConvex()
  const { can, email } = useStaff()
  const logExport = useMutation(api.admin.analytics.logExport)
  const [scope, setScope] = useState('all')
  const [includeLearners, setIncludeLearners] = useState(false)
  const [county, setCounty] = useState('')
  const [status, setStatus] = useState<'all' | 'completed' | 'in_progress'>('all')
  const [busy, setBusy] = useState(false)
  const [progress, setProgress] = useState('')
  const [askReason, setAskReason] = useState(false)

  async function build(reason?: string): Promise<boolean> {
    setBusy(true)
    setProgress('Reading summary…')
    try {
      const [overview, trend] = await Promise.all([
        convex.query(api.admin.analytics.overview, {}),
        convex.query(api.admin.analytics.trend, { days }),
      ])
      const chosen = overview.programs.filter((p) => scope === 'all' || p.id === scope)
      const now = Date.now()
      const sheets: Sheet[] = [
        {
          name: 'About',
          rows: [
            ['Item', 'Value'],
            ['Report', 'Mwalimu AI learning analytics'],
            ['Generated at (UTC)', stamp(now)],
            ['Generated by', email],
            ['Programs', scope === 'all' ? 'All programs' : (chosen[0]?.title ?? scope)],
            ['Daily activity window', `Last ${days} days (Kenya time)`],
            ['Learner rows filter', includeLearners ? `County: ${county || 'any'}; status: ${status.replace('_', ' ')}` : 'Not included'],
            ['Completion rate', 'Certificates issued ÷ learners who started the program'],
            ['Avg progress', 'Lessons completed ÷ (learners started × lessons in the program)'],
            ['Avg improvement', 'Average post-test % minus average pre-test % (different learners may have taken each)'],
            ['Active learners', 'Learners who opened the app that day; a learner counts once per day'],
          ],
        },
        {
          name: 'Programs',
          rows: [
            ['Program', 'Lessons', 'Started', 'Completed (certificates)', 'Completion rate %', 'Avg progress %', 'Pre-tests taken', 'Avg pre-test %', 'Post-tests taken', 'Avg post-test %', 'Avg improvement (pts)', 'Assignments submitted', 'Avg days to certificate'],
            ...chosen.map((p): Cell[] => [p.title, p.totalLessons, p.enrolled, p.completed, p.completionRate, p.avgProgressPct, p.preTaken, p.avgPrePct, p.postTaken, p.avgPostPct, p.preTaken && p.postTaken ? Math.round((p.avgPostPct - p.avgPrePct) * 10) / 10 : null, p.assignments, p.avgDaysToCertificate]),
          ],
        },
        {
          name: 'Lesson funnel',
          rows: [
            ['Program', 'Module', 'Lesson', 'Lesson key', 'Learners who completed it', '% of learners started', 'Counts toward completion'],
            ...chosen.flatMap((p) => p.funnel.map((l): Cell[] => [p.title, l.module, l.title, l.key, l.completions, l.pctOfEnrolled, l.active])),
          ],
        },
        {
          name: 'Daily activity',
          rows: [
            ['Date', 'Active learners', 'Learners who did a lesson', 'Learners who used a tool', 'Assessments'],
            ...trend.map((d): Cell[] => [d.date, d.active, d.lessons, d.tools, d.assessments]),
          ],
        },
      ]

      let learnerRows = 0
      if (includeLearners) {
        const rows: Cell[][] = [
          ['Name', 'Email', 'Phone', 'County', 'School', 'Experience level', 'Account', 'Program', 'Lessons completed', 'Lessons in program', 'Progress %', 'Last lesson completed', 'Pre-test %', 'Post-test %', 'Assignment submitted', 'Certificate', 'Started', 'Last activity'],
        ]
        outer: for (const p of chosen) {
          let cursor: string | null = null
          for (;;) {
            const res: Awaited<ReturnType<typeof convex.query<typeof api.admin.analytics.learners>>> = await convex.query(api.admin.analytics.learners, {
              programId: p.id,
              paginationOpts: { numItems: PAGE, cursor },
              county: county.trim() || undefined,
              status,
            })
            for (const r of res.page) {
              rows.push([r.name, r.email, r.phone, r.county, r.school, r.experienceLevel, r.accountStatus, r.programTitle, r.lessonsCompleted, r.lessonsTotal, r.progressPct, r.lastLesson, r.preScorePct, r.postScorePct, r.assignmentSubmitted, r.certificate, stamp(r.startedAt), stamp(r.lastActivityAt)])
            }
            learnerRows = rows.length - 1
            setProgress(`Reading learners… ${learnerRows.toLocaleString()} rows`)
            if (learnerRows >= MAX_ROWS) {
              toast.warning(`Stopped at ${MAX_ROWS.toLocaleString()} rows. Narrow the filters to export the rest.`)
              break outer
            }
            if (res.isDone) break
            cursor = res.continueCursor
          }
        }
        // Record who took learner-level data before it leaves the console.
        await logExport({ reason: reason ?? '', programs: chosen.map((p) => p.id), county: county.trim() || undefined, status, rows: learnerRows })
        sheets.push({ name: 'Learners', rows })
      }
      downloadXlsx(`mwalimu-learning-analytics-${new Date().toISOString().slice(0, 10)}.xlsx`, sheets)
      toast.success(includeLearners ? `Exported ${learnerRows.toLocaleString()} learner rows` : 'Exported')
      return true
    } catch (e) {
      toast.error(e instanceof Error ? 'The export failed. Please try again.' : 'The export failed.')
      return false
    } finally {
      setBusy(false)
      setProgress('')
    }
  }

  return (
    <section className="rounded-lg border bg-background p-4" aria-labelledby="export-h">
      <h2 id="export-h" className="font-semibold">Export to Excel</h2>
      <p className="mb-3 text-sm text-muted-foreground">
        One workbook with a summary per program, the lesson-by-lesson funnel and daily activity. Add learner rows for a deep dive on each person.
      </p>
      <div className="grid gap-3 sm:grid-cols-2">
        <Field label="Programs">
          <select className={selectClass} value={scope} onChange={(e) => setScope(e.target.value)}>
            <option value="all">All programs</option>
            {programs.map((p) => (
              <option key={p.id} value={p.id}>{p.title}</option>
            ))}
          </select>
        </Field>
        {can('analytics.export') && (
          <label className="flex items-center gap-2 self-end pb-2 text-sm">
            <input type="checkbox" checked={includeLearners} onChange={(e) => setIncludeLearners(e.target.checked)} />
            Include one row per learner (names, emails and progress)
          </label>
        )}
      </div>
      {includeLearners && (
        <div className="mt-3 grid gap-3 sm:grid-cols-2">
          <Field label="County (optional, exact name)">
            <Input value={county} onChange={(e) => setCounty(e.target.value)} placeholder="e.g. Nakuru" />
          </Field>
          <Field label="Completion">
            <select className={selectClass} value={status} onChange={(e) => setStatus(e.target.value as typeof status)}>
              <option value="all">Everyone who started</option>
              <option value="completed">Completed</option>
              <option value="in_progress">Still in progress</option>
            </select>
          </Field>
        </div>
      )}
      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Button disabled={busy} onClick={() => (includeLearners ? setAskReason(true) : void build())}>
          {busy ? 'Preparing…' : 'Download .xlsx'}
        </Button>
        <span className="text-sm text-muted-foreground" aria-live="polite">{progress}</span>
      </div>
      {includeLearners && (
        <p className="mt-2 text-xs text-muted-foreground">
          Learner rows contain personal data. The export is recorded in the audit log with your reason. Limit {MAX_ROWS.toLocaleString()} rows.
        </p>
      )}
      <ReasonDialog
        open={askReason}
        onOpenChange={setAskReason}
        title="Export learner data?"
        description="Say why you need personal data in this export. It is saved in the audit log."
        confirmLabel="Export"
        onConfirm={(reason) => build(reason)}
      />
    </section>
  )
}
